name: Sort JSON Files

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pkg/kor/exceptions/**'

jobs:
  sort_json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Sort JSON files
      run: |
        find pkg/kor/exceptions -name '*.json' -exec sh -c 'jq "map(sort_by(.Namespace, .ResourceName))" {} > {}.tmp && mv {}.tmp {}' \;

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Automatically sorted JSON files"

    - name: Push changes to current branch
      run: |
        git push origin HEAD:$(echo ${GITHUB_REF#refs/heads/})
