name: Check Exceptions JSON Files Sorting

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pkg/kor/exceptions/**'
  
jobs:
  sort_json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Check Exceptions JSON Files Sorting
      run: |
        find pkg/kor/exceptions/ -name '*.json' -exec sh -c 'SORTED=$(jq "with_entries(.value |= sort_by(.Namespace, .ResourceName))" {}); if [ "$(jq . {})" != "$SORTED" ]; then echo "{} is not sorted"; fi;' \;
